version: 2.1
jobs:
  executor: node/default
  steps:
    - checkout
    - node/install-packages:
      cache-path: 
      override-ci-command: npm install
    - run: npm run test
workflows:
  test_my_app:
    jobs:
      - test
