version: '2.1'
orbs:
  node: circleci/node@4.7.0
jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test

  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

workflows:
  test_my_app:
    jobs:
      - test
      - say-hello
